### ISSUE TITLE
Getting an I/O error from serial port

### ISSUE THREAD

**Issue by brunon** [sbcshop/Air-Monitoring-HAT#4]
Fresh install of Raspian on a new Pi4 board
I installed all the dependencies, have the HAT plugged in, the red power led on the board is turned on
I enabled I2C and Serial port hardware in raspi-config
Running any of the Python files provided results in a "I/O error" while reading from the serial port
I tried running as pi user and as root (via sudo), same result

Even the OLED display does not seem to work, when running the "display_on_oled_example.py" file I get this which seems to indicate it is failing at trying to initialize the OLED screen

```
Traceback (most recent call last):
  File "/home/pi/Air-Monitoring-HAT/display_on_oled_example.py", line 19, in <module>
    oled_display = SSD1306()
  File "/home/pi/Air-Monitoring-HAT/oled_091.py", line 98, in __init__
    self.InitDisplay()
  File "/home/pi/Air-Monitoring-HAT/oled_091.py", line 128, in InitDisplay
    self.WriteCommand(DISPLAY_ON)
  File "/home/pi/Air-Monitoring-HAT/oled_091.py", line 122, in WriteCommand
    self.i2c_write(register=0x00, data=cmd)
  File "/home/pi/Air-Monitoring-HAT/oled_091.py", line 77, in i2c_write
    self.bus.write_byte_data(self.address, register, data)
OSError: [Errno 121] Remote I/O error
```

Running i2cdetect returns this, but I don't know how to interpret this information

```
$ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
```

I am running with Python 3

**Comment by brunon** [comment]
Turns out it was my error. I was using a case that made it difficult to squeeze in the HAT and it wasn't properly plugged in - the power connection was there but not some of the other pins. Please ignore this

Note that I had to change to /dev/ttyAMA0 to make it work however as /dev/ttyS0 did not work

**Comment by TomaszWaszczyk** [comment]
Have you got any pollution? I got this:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/workspaces/Air-Monitoring-HAT/Air_Monitoring_GUI.py", line 258, in read_data
    pm_1, pm_25, pm_10 = robot.update_data()
  File "/home/pi/workspaces/Air-Monitoring-HAT/air_monitoring_hat.py", line 51, in update_data
    self.read_value()
  File "/home/pi/workspaces/Air-Monitoring-HAT/air_monitoring_hat.py", line 36, in read_value
    reading = self.sensor.read()
  File "/home/pi/workspaces/Air-Monitoring-HAT/pms_a003.py", line 77, in read
    raise SensorException("No message received")
pms_a003.SensorException: No message received
```
and then this:

```
pi@raspberrypi:~/workspaces/Air-Monitoring-HAT $ sudo python3 display_on_oled_example.py 
PM 1.0 : 24 	PM 2.5 : 29 	PM 10 : 31
Traceback (most recent call last):
  File "/home/pi/workspaces/Air-Monitoring-HAT/display_on_oled_example.py", line 28, in <module>
    values = air_mon.read()
  File "/home/pi/workspaces/Air-Monitoring-HAT/pms_a003.py", line 77, in read
    raise SensorException("No message received")
pms_a003.SensorException: No message received
pi@raspberrypi:~/workspaces/Air-Monitoring-HAT $ sudo python3 display_on_oled_example.py 
Traceback (most recent call last):
  File "/home/pi/workspaces/Air-Monitoring-HAT/display_on_oled_example.py", line 28, in <module>
    values = air_mon.read()
  File "/home/pi/workspaces/Air-Monitoring-HAT/pms_a003.py", line 77, in read
    raise SensorException("No message received")
pms_a003.SensorException: No message received
pi@raspberrypi:~/workspaces/Air-Monitoring-HAT $ 
```

How to make it update-able on a screen?

**Solved:** Using the hints it is working!! Exactly saying this:

> 
> "To manually change the settings, edit the kernel command line with sudo nano /boot/cmdline.txt. Find the console entry that refers to the serial0 device, and remove it, including the baud rate setting. It will look something like console=serial0,115200. Make sure the rest of the line remains the same, as errors in this configuration can stop the Raspberry Pi from booting."
> 
> Just this line needed to be edited.
> 
> Here is link https://www.raspberrypi.org/documentation/configuration/uart.md
